#cloud-config

timezone: America/Toronto

users:
  - default
  - name: ${user}
    groups: [sudo]
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_pub}

package_update: true
packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "done" > /tmp/cloud-config.done

